version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆"
    reviewers:
      - "tomrijnbeek"
    groups:
      production-deps:
        dependency-type: "production"
      development-deps:
        dependency-type: "development"
