version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:latest-v8.x
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: circleci/node:latest-v8.x
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run-script build

  lint:
    docker:
      - image: circleci/node:latest-v8.x
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run-script lint

  deploy:
    docker:
      - image: circleci/node:latest-v8.x
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: sudo npm install -g pm2
      - run: echo 'clanquest.org,45.33.99.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBcUo9JpxttuJV5AHthqze1F/DrlfDinZPSY7ex9nxy1D28z2lt8AIyYImHhK4JWBId6066fvXM7lN3CEJyEE5k=' >> ~/.ssh/known_hosts
      - run: pm2 deploy ecosystem.config.js production

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master
