name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ matrix.node-version }}
